### ISSUE TITLE
Training on Pascal VOC 2007

### ISSUE THREAD

**Issue by caojiawenn** [facebookresearch/deepcluster#20]
When training the model on Pascal VOC2007 for clustering,  is the model randomly initialized ? or initialized with the parameters pre-trained on ImageNet?

**Comment by mathildecaron31** [comment]
Hi,

We do not train the model on Pascal VOC2007 for clustering.

We pre-train a model with a joint clustering and classification objective on ImageNet without the labels.
Then, in order to evaluate the quality of the features learned during this pre-training stage we use our weights as initialization to solve tasks (classification, object detection, segmentation) on Pascal VOC2007. In other words, the model is initialized with the weights that we leaned with deepcluster on ImageNet (**without label**).

Hope it helps
