### ISSUE TITLE
Request for cluster assignment list

### ISSUE THREAD

**Issue by creiser** [facebookresearch/deepcluster#4]
Hello,

for an experiment I need the cluster assignment resulting from this algorithm. I would get it myself but at the moment I do not have sufficient RAM to store the complete feature matrix. Therefore I am kindly asking if someone of the authors or somebody else who has run the experiment might be so kind and upload this file for me.

Specifically I need the clustering resulting from the provided pre-trained VGG model. I do not need the feature vectors but only the content of `deepcluster.images_list` which already gets saved to the `exp/1/clusters` file (see line 207 in `main.py`), so there might be the chance that somebody could upload it for me that has already run the experiment for at least one epoch with the pretrained model.

Thanks in advance,
Chris

**Comment by mathildecaron31** [comment]
Hi Chris,
Thank you so much for your message. It is actually a good idea to release the cluster assignments as well since our method, in addition to pre-trained filters, provides a clustering of the data. I have added the cluster assignments at the last epoch of training for both the AlexNet and VGG-16 models for download in the README.
