### ISSUE TITLE
why not use resnet?

### ISSUE THREAD

**Issue by daijing5763** [facebookresearch/deepcluster#68]
resnet is more pwerful，why not use?

**Comment by mathildecaron31** [comment]
Hi,
At the time of the publication (2 years ago), most self-supervised methods were using AlexNet and VGG-16 that's why we did not try ResNet-50. Please see our new repo for an implementation of DeepCluster-v2 with ResNet-50: [https://github.com/facebookresearch/swav](https://github.com/facebookresearch/swav)

**Comment by daijing5763** [comment]
Thank you for your reply
