### ISSUE TITLE
AttributeError: 'CIFAR10' object has no attribute 'imgs'

### ISSUE THREAD

**Issue by Hiiragi0107** [facebookresearch/deepcluster#74]
Hello.
I tried with the CIFAR10 dataset and got an error like the one in the title.
I would like to know how to solve this problem.
This may be an elementary question, but thank you for your help.

WARNING clustering 50000 points to 10000 centroids: please provide at least 390000 training points
Traceback (most recent call last):
  File "main.py", line 333, in <module>
    main(args)
  File "main.py", line 166, in main
    dataset.imgs)
AttributeError: 'CIFAR10' object has no attribute 'imgs'

**Comment by mathildecaron31** [comment]
Hi,
This code is written to work with "ImageFolder" dataset (https://pytorch.org/docs/stable/torchvision/datasets.html#imagefolder). If you use it with another dataset you would need to perform some adaptations because for example CIFAR10 dataset (https://pytorch.org/docs/stable/_modules/torchvision/datasets/cifar.html#CIFAR10) does not have an `imgs` attribute.

**Comment by Hiiragi0107** [comment]
Thanks for the reply.
Once I converted cifar10 to jpg format, I loaded it with ImageFolder.
It worked well.
Thanks.

**Comment by happy20200** [comment]
> Thanks for the reply. Once I converted cifar10 to jpg format, I loaded it with ImageFolder. It worked well. Thanks.

i meet the same problem, but cant solve, please tell me how to converted cifar10 to jpg format
