### ISSUE TITLE
cluster low level features?

### ISSUE THREAD

**Issue by daniiki** [facebookresearch/deepcluster#75]
Hi, 
I have a dataset with images that display dotted font and a white background. The images have different kind of artifacts for example pollution or scratches. I would like to cluster theses images according to the different kind of artifacts. Do you think this is possible with your code? I fear that it will cluster images depending on the font and not depending on the artifacts. 
I found out that you have also a newer code, will it maybe work better with the newer code?

**Comment by mathildecaron31** [comment]
Hi,

Deepcluster-v2 that we presented in (https://arxiv.org/abs/2006.09882) is more stable and gets better performance than deepcluster. Since there is no correspondance between two consecutive assignments in deepcluster, the classification head learned during an assignment becomes irrelevant for the following one. Thus, this classification head needs to be re-set at each new assignment which considerably disrupts the convnet training. For this reason, in deepcluster-v2 we simply replace this classification head by the centroids obtained with k-means clustering. In other words it means that instead of learning a classification head from scratch, we perform explicit comparison between features and centroids. 

To get clusters on the artifacts and not on the font I would recommend to perform appropriate data augmentation during training so that the clusters become font invariant. However I'm not sure if this is possible for you to create font-based data augmentation.

Hope that helps.

**Comment by daniiki** [comment]
Thank you for this detailed answer! Why is the deepclusteringv2 code not in this repository, but in the SwaV repository? Can you still use the files of this repo, but with deepclusteringv2.py? Especially the visualization scripts?

**Comment by mathildecaron31** [comment]
I put deepclusteringv2 code in swav repository because I presented deepclusteringv2 and swav models in the same paper.

I think you would need to adapt the visualization scripts to work with a ResNet-50 architecture.
