### ISSUE TITLE
Do I need labels or pseudo-labels as input for clustering?

### ISSUE THREAD

**Issue by hahmad2008** [facebookresearch/deepcluster#80]
If I have only a bunch of images without labels or tags, can I use the deepcluster for clustering them? Is it fully unsupervised?

**Comment by enaserianhanzaei** [comment]
I believe you can. If you read the paper, in each iteration the model is trying to optimize two optimization problems, first, assignment of images to different clusters and second, using these assignment as pseudo label to optimize the classification problem (then backward that loss through the network). So at each iteration we should have the matrix of K x N of assignment of each image to each cluster. 

At the end of each epoch the result of the clustering is saved. 
cluster_log.log(deepcluster.images_lists)
'

**Comment by hahmad2008** [comment]
Thank you @enaserianhanzaei 
But from the paper, they said that the pseudo labels are given. 

![image](https://user-images.githubusercontent.com/68266028/104854675-c5559080-5910-11eb-92b3-25cac18b28a9.png)

**Comment by enaserianhanzaei** [comment]
from the pseudo-labels they mean the clustering results. Generally, they are training a CNN to learn the representation of the images. But the main problem in computer vision is the lack of labeled data, it is very expensive to label huge amount of data. so, in order to tackle this problem, this paper is proposing a way to learn this representation through unsupervised learning, or clustering here. Therefore, what it does is to simply cluster the data at the end of each round, use the clustering results as the pseudo-labels and then feed it to a classification problem, finally, backward the loss from classification through network to update the weights.  

So, the main goal of this approach is to learn the representation of the images without the need of annotation. However, it also does the clustering in each round, so, you can simply access to the clustering results as I mentioned earlier.

**Comment by hahmad2008** [comment]
What is the initial pseudo labels? and does this affect the training process? if the initial value of these labels is random values.

**Comment by enaserianhanzaei** [comment]
Initially, CNN's weights are randomly initialized and consequently, the image representations are kinda random, and so the clustering results which are the pseudo code are kinda random. 

you really need to read the paper properly and study the code, it's not that difficult.

**Comment by hahmad2008** [comment]
Thank you @enaserianhanzaei 
But as I read from the paper that there are two different things in the equation:
- pseudo labels **y**
-  cluster assignment **z**
If they are the same thing, then why there are y and z?

**Comment by enaserianhanzaei** [comment]
These sentences are from the paper 

''We cluster the output of the convnet and use the subsequent cluster assignmentsas “pseudo-labels” to optimize Eq. (1). This deep clustering (DeepCluster) approach iteratively learns the features and groups them''

""k-means takes a set of vectors as input, in our case the features fθ(xn) produced by the convnet, and clusters them into k distinct groups based on a geometric criterion. More precisely, it jointly learns a d×k centroid matrix C and the cluster assignments yn of each image n by solving the following problem:""


I really cannot help more.

**Comment by mathildecaron31** [comment]
Hello there

@enaserianhanzaei  thanks a lot for helping :). 

@hahmad2008  everything @enaserianhanzaei said is right. The method is fully unsupervised so you do not need to provide any tags or labels.

Pseudo labels and the cluster assignments are the same thing and are denoted `y` in our paper (https://arxiv.org/pdf/1807.05520.pdf). See equations (1) and (2)
