### ISSUE TITLE
A problem why use different optimizer for top layer and other layers

### ISSUE THREAD

**Issue by siyuan2018** [facebookresearch/deepcluster#82]
Hi Dear authors, when I checked the code, I find it actually use different optimizers for top layer and other layers. I am wondering the reason to do so, thank you!

**Comment by mathildecaron31** [comment]
Hi,

Sorry for the delay of my reply.

I used two optimizers for the backbone and the last layer because we are re-initializing the last layer after every epoch. TBH, this is not the most elegant implementation and you could definitely use one unique optimizer (though not with PIC clustering where the number of clusters can change at every different clustering)

**Comment by hanghu1024** [comment]
Hi mathildecaron31, do you mean this re-initialization of classifier layer at every epoch aims to handle the change of number of clusters? If I stay with a fixed number of clusters, like using k-mean, can I use a pre-defined classifier layer and one unique optimizer?
